#!/bin/bash

_log_info() { echo "--- $1 ---"; }

if [ "$(uname -s)" = "Darwin" ]; then
    brew_prefix=/opt/homebrew/bin/brew
else
    brew_prefix=/home/linuxbrew/.linuxbrew/bin/brew
fi

_install_homebrew() {
    if ! command -v $brew_prefix/brew &>/dev/null; then
        _log_info "Install homebrew"
        yes | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
}

_install_upgrade_homebrew_packages() {
    _log_info "Installing/upgrading homebrew packages"
    cd "$HOME" || return
    HOMEBREW_BUNDLE_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/homebrew/Brewfile" $brew_prefix/brew bundle
    cd - || return
}

_update_mise_plugins() {
    _log_info "Updating mise plugins"
    $brew_prefix/mise plugin update --yes
}

_install_and_upgrade_mise_dependencies() {
    _log_info "Installing mise dependencies"
    cd "$HOME" || return
    $brew_prefix/mise install --yes
    $brew_prefix/mise upgrade --yes
    cd - || return
}

_decrypt_yadm_files() {
    _log_info "Decrypting yadm files"
    $brew_prefix/yadm decrypt
}

_install_homebrew
_install_upgrade_homebrew_packages
_update_mise_plugins
_install_and_upgrade_mise_dependencies
_decrypt_yadm_files

_log_info "Installation complete"
