[tools]
# mise plugins list https://github.com/jdx/mise/blob/main/registry.toml
# mise search {fuzzy}
# aqua g

"aqua:bensadeh/tailspin" = "latest"
"aqua:snyk/cli" = "latest"
"aqua:tealdeer-rs/tealdeer" = "latest"
"ubi:abhinav/git-spice" = { version = "latest", exe = "gs", rename_exe = "git-spice" }
"ubi:cormacrelf/dark-notify" = "latest"
"ubi:https://github.com/plantuml/plantuml/releases/download/v1.2025.9/plantuml-1.2025.9.jar" = { version = "1.2025.9", rename_exe = "plantuml" }
amazon-ecr-credential-helper = "latest"
aws-cli = "latest"
bat = "latest"
bun = "latest"
carapace = "latest"
coreutils = "latest"
delta = "latest"
eza = "latest"
fzf = "latest"
gh = "latest"
jq = "latest"
k9s = "latest"
kubecolor = "latest"
neovim = "latest"
opencode = "latest"
pre-commit = "latest"
ripgrep = "latest"
usage = "latest"
yadm = "latest"

[tools."http:atlassian-cli"]
version = "latest"
rename_exe = "acli"
platforms.macos-x64.url = "https://acli.atlassian.com/darwin/latest/acli_darwin_amd64/acli"
platforms.macos-arm64.url = "https://acli.atlassian.com/darwin/latest/acli_darwin_arm64/acli"
platforms.linux-x64.url = "https://acli.atlassian.com/linux/latest/acli_linux_amd64/acli"
platforms.linux-arm64.url = "https://acli.atlassian.com/linux/latest/acli_linux_arm64/acli"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
